# Taps
tap "homebrew-zathura/zathura"
tap "arimxyer/tap"
tap "gromgit/brewtils"
tap "sourcegraph/src-cli"

# --- CLI Utilities ---
brew "mas"
brew "tree"
brew "bat"
brew "eza"
brew "git"
brew "git-extras"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "lesspipe"
brew "tealdeer"
brew "hexyl"
brew "cloc"
brew "chafa"
brew "asciinema"
brew "lazygit"
brew "joshuto"
brew "just"
brew "oh-my-posh"
brew "doctl"
brew "rainfrog"
brew "worktrunk"
brew "zoxide"

# --- Editors ---
brew "neovim"

# --- Languages & Toolchains ---
brew "go"
brew "golangci-lint"
brew "hugo"
brew "nvm"
brew "pyenv"
brew "pyenv-virtualenv"
brew "tectonic"
brew "gs"
# brew "slither-analyzer"

# --- Dev Tools ---
brew "docker"
brew "graphviz"
brew "sourcegraph/src-cli/src-cli"
brew "gromgit/brewtils/taproom"

# --- Document Viewers ---
brew "zathura"
brew "zathura-pdf-poppler"

# --- System Monitoring ---
brew "btop"
brew "mactop"
brew "zenith"
brew "bottom"
brew "bandwhich"
brew "diskus"
brew "dua-cli"

# --- Libraries & Build Tools ---
brew "readline"
brew "secp256k1"
brew "ccache"
brew "pkgconfig"
brew "cmake"
brew "libsodium"
brew "poppler"
brew "pillow"

# --- AI/ML ---
brew "llmfit"
brew "arimxyer/tap/models"

# --- Cask Apps ---
cask "google-chrome"
cask "firefox"
cask "1password"
cask "obsidian"
cask "todoist-app"
cask "slack"
cask "loom"
cask "raycast"
cask "bruno"
cask "notion-calendar"
cask "keepingyouawake"
cask "showyedge"
cask "outline-manager"
cask "transmission"
cask "vlc"
cask "hammerspoon"
cask "karabiner-elements"
cask "claude-code"

# --- Editors & Terminals ---
cask "ghostty"
cask "kitty"
cask "visual-studio-code"
cask "zed"
cask "neovide-app"
# cask "jimeh/emacs-builds/emacs-app"

# --- Fonts ---
cask "font-juliamono"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-0xproto-nerd-font"
cask "font-agave-nerd-font"
cask "font-anonymice-nerd-font"
cask "font-aurulent-sans-mono-nerd-font"
cask "font-bigblue-terminal-nerd-font"
cask "font-bitstream-vera-sans-mono-nerd-font"
cask "font-blex-mono-nerd-font"
cask "font-caskaydia-mono-nerd-font"
cask "font-code-new-roman-nerd-font"
cask "font-commit-mono-nerd-font"
cask "font-cousine-nerd-font"
cask "font-d2coding-nerd-font"
cask "font-departure-mono-nerd-font"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-envy-code-r-nerd-font"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-geist-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-hasklug-nerd-font"
cask "font-heavy-data-nerd-font"
cask "font-hurmit-nerd-font"
cask "font-im-writing-nerd-font"
cask "font-intone-mono-nerd-font"
cask "font-lekton-nerd-font"
cask "font-liberation-nerd-font"
cask "font-lilex-nerd-font"
cask "font-monaspice-nerd-font"
cask "font-monofur-nerd-font"
cask "font-mononoki-nerd-font"
cask "font-noto-nerd-font"
cask "font-opendyslexic-nerd-font"
cask "font-overpass-nerd-font"
cask "font-proggy-clean-tt-nerd-font"
cask "font-recursive-mono-nerd-font"
cask "font-shure-tech-mono-nerd-font"
cask "font-terminess-ttf-nerd-font"
cask "font-noto-sans-symbols-2"
